version: "3.8"
services:
  ze-mongo:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
    - /mongo:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: unless-stopped

  ze-api:
    image: 'ze-delivery-api:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - ze-mongo
    links:
      - ze-mongo